# Generated by Django 2.0 on 2019-12-13 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myArt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='posted_by',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 12, 13, 16, 16, 8, 878112)),
        ),
    ]
